I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 184, in script
    viv "Oh, I found it here! Basically all you have to do is apply for it using
ValueError: unsupported format character 'a' (0x61) at index 161

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 184, in script
    viv "Oh, I found it here! Basically all you have to do is apply for it using
  File "renpy/ast.py", line 706, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1373, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character 'a' (0x61) at index 161

